import { NextApiRequest, NextApiResponse } from "next";
export default function Script(req: NextApiRequest, res: NextApiResponse) {
  const script = {
    "L.2.wav": "what are you looking at John?",
    "L.3.wav": "It’s a picture of my elementary school trip six years ago",
    "L.4.wav": "Which one are you in the picture?",
    "L.5.wav": "Take a guess who! .",
    "L.6.wav": "I’m wearing glasses ",
    "L.7.wav": "and holding a baseball cap in my hand",
    "L.8.wav": " I have no idea.",
    "L.17.wav": "No one looks like you.",
    "L.19.wav": "I am also running to the bench ",
    "L.21.wav": "to take the picture together. ",
    "L.23.wav": "It was so funny.",
    "L.25.wav": "This must be you.",
    "L.27.wav": " You’ve changed a lot",
    "L.29.wav": " Have I?",
    "L.31.wav": " This is my favorite old picture.",
    "L.37.wav": "Hi, Sam! ",
    "L.39.wav": "What’s up ?",
    "L.41.wav": "Not much.",
    "L.43.wav": " Actually .",
    "L.45.wav": "I’ve decided to go to Jeonju with my uncle this Saturday",
    "L.47.wav": "Really?",
    "L.49.wav": "I went there last week.",
    "L.51.wav": "I know.",
    "L.53.wav": "That’s why I’m calling you ",
    "L.59.wav": " Well, I loved Jeonju Hanok Village very much.",
    "L.61.wav": " I’ll have to check that out",
    "L.63.wav": " By the way, ",
    "L.65.wav": "do you have a map of the city I can borrow?",
    "L.67.wav": "Sure",
    "L.69.wav": " It will help you plan your trip",
    "L.71.wav": "And visit the official Jeonju City website, too",
    "L.73.wav": "Okay, I will",
    "L.77.wav": "How long does it take to the station?",
    "L.79.wav": "It takes 15 minutes by bike.",
    "L.81.wav": " How often do you bike?",
    "L.83.wav": "Two or three times a week.",
    "L.85.wav": "You are not allowed ",
    "L.87.wav": "to ride a bike on this running track.",
    "L.89.wav": "Oh, I didn’t know that.",
    "L.91.wav": " I’ll get off of it .",
    "L.95.wav": "Where did you buy your mountain bike?",
    "L.97.wav": "I bought it on the Internet.",
    "L.99.wav": "What is the best exercise for health?",
    "L.103.wav": "Biking is ",
    "L.105.wav": "definitely the best ",
    "L.106.wav": "for teenagers.",
    "L.111.wav": "Hello. How can I help you?",
    "L.113.wav": "Hi. I am looking for a watch.",
    "L.115.wav": "Okay. How about this round one?",
    "L.117.wav": " It’s very popular",
    "L.119.wav": "I don’t want a digital watch.",
    "L.121.wav": "All right. Then, how about this basic one with ",
    "L.123.wav": " 12 numbers on it?",
    "L.125.wav": " That’s too normal.",
    "L.127.wav": "Then, how about one of these two watches?",
    "L.129.wav": "One has four numbers on it ",
    "L.131.wav": "and the other doesn’t have any numbers.",
    "L.133.wav": "Hmm, I like the one with no numbers on it.",
    "L.139.wav": "Hello. Can I talk to Mr. Anderson?",
    "L.141.wav": " This is he. Who is calling, please?",
    "L.143.wav": "This is Sam Brown’s mother.",
    "L.145.wav": "I’m calling to let you know he broke his leg ",
    "L.147.wav": "That’s too bad.",
    "L.149.wav": "That’s why he is absent from school today.",
    "L.151.wav": "Yes. He broke his leg while playing soccer yesterday.",
    "L.153.wav": "I see. Where is he now?",
    "L.155.wav": " He is in the hospital",
    "L.157.wav": "and the doctor told him",
    "L.159.wav": "he would have to stay there for a week.",
    "L.161.wav": "Okay. I will visit him with some of his classmates tomorrow.",
    "L.165.wav": "Jessy, I’m so sorry for being late.",
    "L.167.wav": " That’s okay, Mike. But why are you so late?",
    "L.169.wav": "There was terrible traffic coming here!",
    "L.171.wav": "Well, let’s get into the theater. ",
    "L.173.wav": "The concert is about to start.",
    "L.175.wav": "What is that sign for?",
    "L.177.wav": " To wave when the band performs,",
    "L.179.wav": "I wrote the band members’ names on it.",
    "L.181.wav": "You are a big fan of them",
    "L.183.wav": "Definitely.",
    "L.185.wav": " You don’t know how long I have waited for this moment.",

    "L.191.wav": "Could you give me a wake-up call ?",
    "L.193.wav": " Sure. When would you like the call?",
    "L.195.wav": " Can I get a refund on this sweater ?",
    "L.197.wav": "What’s the problem with it?",
    "L.199.wav": "I’d like to make a reservation tonight.",
    "L.201.wav": "For how many, sir?",
    "L.203.wav": "Where did you see the movie last week?",
    "L.205.wav": " I moved to a new apartment over there.",
    "L.207.wav": "We are running out of time , Judy.",
    "L.209.wav": " I know. I am going as fast as I can.",
    "L.213.wav": " I heard you stayed in China for a few years, Mina.",
    "L.215.wav": "Yes, I did. Why?",
    "L.217.wav": "I have a Chinese pen pal.",
    "L.219.wav": "He will visit Korea this summer .",
    "L.221.wav": " That’s great. ",
    "L.223.wav": " I guess you must be studying Chinese nowadays.",
    "L.225.wav": "Yes, but it’s difficult to pronounce some words .",
    "L.227.wav": "Can you help me if you have time on the weekend?",
    "L.229.wav": "Of course, I can.",
    "L.231.wav": " I am available every Sunday afternoon.",
    "L.233.wav": "Thanks.",
    "L.235.wav": "And I will introduce him to you later.",
    "L.237.wav": "We can have fun together.",
    "L.239.wav": "Terrific.",
    "L.243.wav": "It was a wonderful summer vacation for me, Sujin.",
    "L.245.wav": "Time really flies. ",
    "L.247.wav": "I cannot believe it’s time for you to leave Korea.",
    "L.249.wav": "I want to visit Korea again someday. I’m glad to hear that.",
    "L.251.wav":
      "You know, I really appreciate you helping me to experience Korean food and culture.",
    "L.253.wav": "It was my pleasure.",
    "L.255.wav": "I will never forget what you’ve done for me.",
    "L.259.wav": "Hello. How much are these cakes?",
    "L.261.wav": "The large one is $10, and the small one is $8.",
    "L.263.wav": "Okay. I’d like two small ones.",
    "L.265.wav": " Do you need anything else? ",
    "L.267.wav": "Fruit juice is only $2 a bottle.",
    "L.269.wav": "Then I’ll take two bottles of juice please.",
    "L.271.wav": "And here is my loyalty card.",
    "L.273.wav": "All right. ",
    "L.275.wav": " You’ll get 10% off the total.",
    "L.277.wav": "Thank you.",
    "L.281.wav": " I’m glad to see you found it, ma’am.",
    "L.283.wav": " It wasn’t difficult.",
    "L.285.wav": "I just followed the numbers on the bookshelf as you told me.",
    "L.287.wav": "Good",
    "L.289.wav": " Can I see your I.D. card?",
    "L.291.wav": "Here you are.",
    "L.293.wav": "How long can I keep it ?",
    "L.295.wav": "You can keep it for up to three weeks.",
    "L.297.wav": "Okay. By the way , where are the newspapers and magazines?",
    "L.299.wav": "They’re in Room 5 on the second floor",
    "L.301.wav": "Video materials are available, too.",
    "L.303.wav": "Thank you very much.",
    "L.309.wav": "Hello, students. ",
    "L.311.wav": "This is Ms. Brown, a seventh grade English teacher.",
    "L.313.wav": " The school’s English Essay Contest ",
    "L.315.wav": " will be held on Wednesday, August 27",
    "L.317.wav": "It will be in the Student Hall ",
    "L.319.wav": "from 5 to 6 p.m",
    "L.321.wav": "If you want to participate in the contest,",
    "L.323.wav": "write your name on the registration sheet ",
    "L.325.wav": " in the main teachers’ office.",
    "L.327.wav": " The topic of the essay",
    "L.329.wav": "will not be released until the contest starts.",
    "L.331.wav": " Bookstore gift certificates will be given to the winners.",
    "L.333.wav": "Visit our school website for more information.",
    "L.335.wav": "Thank you.",
    "L.339.wav": " Here is the swimming class brochure for March.",
    "L.341.wav": "Great,",
    "L.343.wav": "let me see it.",
    "L.345.wav": "How about signing up for the Dolphin class with me?",
    "L.347.wav": "It’s $70 a month.",
    "L.349.wav": " I can’t.",
    "L.351.wav": "It’s on Monday to Friday",
    "L.353.wav": " I have a piano lesson on Tuesday and Thursday evening.",
    "L.355.wav": "Then, what about the Whale class?",
    "L.357.wav": "The classes are on Monday, Wednesday, and Friday.",
    "L.359.wav": " Hmm.... I think that would make my week toobusy.",
    "L.361.wav": "I want a swimming class that meets just two days a week.",
    "L.363.wav": " Then there’s only one choice.",
    "L.365.wav": "The Shark class is a 2-day class ",
    "L.367.wav": "that meets on Monday and Friday.",
    "L.369.wav": "That’s much better",
    "L.371.wav": "Besides, it’s not expensive.",
    "L.373.wav": "I was thinking of spending less than $40.",
    "L.375.wav": " Let’s take the one that begins at five.",
    "L.377.wav": "Okay, sounds good.",
    "L.381.wav": "This was very important for cities to grow in world history.",
    "L.383.wav": "That’s why the major cities were located near this.",
    "L.385.wav": " This is a lot of water that keeps moving along like a road.",
    "L.387.wav": "This runs from one place to another",
    "L.389.wav": " and ends up in an ocean or a lake.",
    "L.391.wav": " We can swim or fish in this",
    "L.393.wav": "This is part of our lives, ",
    "L.395.wav": "so we should keep this clean.",
    "L.399.wav": " Emily, you look pale and tired. ",
    "L.401.wav": "What’s the matter?",
    "L.403.wav": "I didn’t get a good night’s sleep last night.",
    "L.405.wav": "Why is that?",
    "L.407.wav": "I was up late working on my science report.",
    "L.409.wav": "I see, but I think you should take a short nap now.",
    "L.411.wav": " I wish I could.",
    "L.413.wav": " But I have to finish it by tomorrow.",
    "L.415.wav": "Then, why don’t you go out for a walk for a while?",
    "L.417.wav": " It will help wake you up .",
    "L.419.wav": "That sounds good.",
    "L.423.wav": "Hello. I would like one adult ticket ",
    "L.425.wav": "to Busan on the 13th.",
    "L.427.wav": " You mean this Friday, right?",
    "L.429.wav": "No. ",
    "L.431.wav": "I want a Saturday ticket.",
    "L.433.wav": "So, do you mean on the 14th of May?",
    "L.435.wav": "Oh, I’m sorry. I was confused.",
    "L.437.wav": "That’s okay. ",
    "L.439.wav": "What time, sir?",
    "L.441.wav": "I’d like a ticket with a departure around 3 p.m.",
    "L.443.wav": "Let me see.... ",
    "L.445.wav": "There’s a seat on the 4 p.m. on Saturday.",
    "L.447.wav": "I will take that.",
    "L.451.wav": " Jacob played basketball every Saturday",
    "L.453.wav": "through a local sports program.",
    "L.455.wav": "His team won every game",
    "L.457.wav": "until they lost the game in the finals ",
    "L.459.wav": "by only a point.",
    "L.461.wav": "Jacob is disappointed with the loss . ",
    "L.463.wav": " His friend Sam wants to encourage Jacob. ",
    "L.465.wav": " In this situation,",
    "L.467.wav": "what would Sam most likely say to Jacob?",

    "L.471.wav":
      " Do you know any place around here where I can get a quick lunch?",
    "L.473.wav": " Well, how about Hamburger Paradise in front of the school?",
    "L.475.wav": " I don’t feel like a burger.",
    "L.477.wav": "I feel like Chinese food.",
    "L.479.wav": "The closest Chinese restaurant is really far from here.",
    "L.481.wav": " How about noodles?",
    "L.483.wav": "That’s not bad. ",
    "L.485.wav": "Is it far from here?",
    "L.487.wav": " No, it’s just across the street from school.",
    "L.489.wav": " Cool. I have to be back in 30 minutes for a club meeting.",
    "L.491.wav": "You are so busy as always .",
    "L.495.wav": "Are you ready for the midterm exams next week?",
    "L.497.wav": "No. I’m worried about them .",
    "L.499.wav": "Worried? You’ve studied a lot for them.",
    "L.501.wav": "And your English is perfect.",
    "L.503.wav": "But math is a huge mountain for me to climb.",
    "L.505.wav": "Oh, I see. ",
    "L.507.wav": " I can help you study math this Saturday .",
    "L.509.wav": "Are you sure? ",
    "L.511.wav": " But I don’t want to bother you.",
    "L.513.wav": "That’s fine with me.",
    "L.515.wav": "Let’s meet at the public library Saturday afternoon.",
    "L.517.wav": "How nice of you!",
    "L.521.wav":
      " Hello. Could you tell me if it’s possible for me to volunteer here for a couple of weeks?",
    "L.523.wav": "Have you ever worked with senior citizens before?",
    "L.525.wav":
      "Yes. I’ve volunteered at a local senior citizen center for 20 hours.",
    "L.527.wav": " That’s a good experience.",
    "L.529.wav": " You are qualified to work here.",
    "L.531.wav": " Great.",
    "L.533.wav": " What kind of work is needed here?",
    "L.535.wav": "Volunteers ",
    "L.537.wav": "are asked to help senior citizens",
    "L.539.wav": "clean their room, ",
    "L.541.wav": " , eat meals",
    "L.543.wav": " and so on.",
    "L.545.wav": "Okay.",
    "L.547.wav": "I will try my best.",
    "L.549.wav": "Can you start volunteering tomorrow?",
  };

  res.json({
    ok: true,
    script,
  });
}
